const postDetails = {
    "1": "<h3>Ubtan Detan Sunscreen Overview</h3><img src='product1.jpg' alt='Mamaearth Ubtan Detan Sunscreen product' style='width:100%; max-height:300px; object-fit:contain; margin-bottom:20px;'><p>Mamaearth Ubtan Detan Sunscreen is a revolutionary skincare product that combines the ancient wisdom of Ubtan with modern detan technology and powerful sun protection. This natural sunscreen offers SPF 50+ protection while gently exfoliating and brightening the skin.</p><p>Key features include:</p><ul><li><strong>Ubtan Exfoliation:</strong> Traditional Indian scrub for removing dead skin cells and impurities.</li><li><strong>Detan Action:</strong> Reduces tan and evens skin tone for a radiant complexion.</li><li><strong>Sunscreen Protection:</strong> Broad-spectrum SPF 50+ to shield against UVA and UVB rays.</li><li><strong>Natural Ingredients:</strong> Made with plant-based, toxin-free components suitable for all skin types.</li></ul><p>Perfect for daily use, this sunscreen helps prevent sun damage, hyperpigmentation, and premature aging. Keywords: Ubtan Detan Sunscreen, natural sunscreen, SPF 50, skin brightening, sun protection.</p>",
    "2": "<h3>Ubtan Detan Sunscreen Ingredients</h3><img src='product1_ingridents.jpg' alt='Mamaearth Ubtan Detan Sunscreen ingredients' style='width:100%; max-height:300px; object-fit:contain; margin-bottom:20px;'><p>Mamaearth Ubtan Detan Sunscreen is formulated with a blend of natural, effective ingredients that provide exfoliation, brightening, and sun protection. Each component is carefully selected for its skin-loving properties.</p><p>Key ingredients include:</p><ul><li><strong>Turmeric (Ubtan):</strong> Natural exfoliant that brightens skin and reduces inflammation.</li><li><strong>Vitamin C:</strong> Powerful antioxidant for detan and collagen production.</li><li><strong>Zinc Oxide:</strong> Mineral sunscreen that provides broad-spectrum protection.</li><li><strong>Chickpea Flour:</strong> Gentle scrub for smooth, glowing skin.</li><li><strong>Aloe Vera:</strong> Soothes and hydrates the skin.</li><li><strong>Neem & Pomegranate:</strong> Antibacterial and nourishing extracts.</li></ul><p>This toxin-free formula is free from parabens, sulfates, and synthetic fragrances, making it safe for sensitive skin. Keywords: natural ingredients, Ubtan ingredients, detan ingredients, sunscreen ingredients, plant-based skincare.</p>",
    "3": "<h3>Ubtan Detan Sunscreen Benefits</h3><img src='product1_description.jpg' alt='Mamaearth Ubtan Detan Sunscreen benefits' style='width:100%; max-height:300px; object-fit:contain; margin-bottom:20px;'><p>Mamaearth Ubtan Detan Sunscreen offers comprehensive benefits for healthy, protected skin. Regular use helps achieve a brighter, more even complexion while safeguarding against sun damage.</p><p>Primary benefits:</p><ul><li><strong>Sun Protection:</strong> SPF 50+ shields against harmful UV rays, preventing sunburn and skin cancer.</li><li><strong>Skin Brightening:</strong> Reduces tan and hyperpigmentation for a radiant glow.</li><li><strong>Exfoliation:</strong> Gently removes dead cells, unclogging pores and improving texture.</li><li><strong>Hydration:</strong> Keeps skin moisturized without greasiness.</li><li><strong>Anti-Aging:</strong> Protects collagen and prevents premature wrinkles.</li><li><strong>Suitable for All:</strong> Works on various skin types, including sensitive and acne-prone.</li></ul><p>Experience the perfect blend of tradition and science with Mamaearth Ubtan Detan Sunscreen. Keywords: sunscreen benefits, Ubtan benefits, detan benefits, skin brightening, sun protection benefits.</p>"
};

const modal = document.getElementById("modal");
const content = document.getElementById("modal-content");
const closeBtn = document.querySelector(".close-modal");

document.querySelectorAll(".read-btn").forEach(btn => {
    btn.onclick = () => {
        const id = btn.getAttribute("data-post");
        content.innerHTML = postDetails[id];
        modal.style.display = "block";
    };
});

closeBtn.onclick = () => modal.style.display = "none";
window.onclick = (e) => { if(e.target == modal) modal.style.display = "none"; }